import type { ProfileRole } from '@/payload-types'

type SeedProfileRole = Omit<ProfileRole, 'createdAt' | 'icon' | 'id' | 'updatedAt'>

const roleIconBase = '/assets/raid-guild-roles'

export const profileRoles: SeedProfileRole[] = [
  {
    title: 'Archer',
    type: 'Design',
    group: 'builder',
    description: 'Graphic design, illustration, visual design, and brand craft.',
    iconPath: `${roleIconBase}/archer.svg`,
    slug: 'archer',
  },
  {
    title: 'Druid',
    type: 'Data Science/Analytics',
    group: 'builder',
    description: 'Research, analytics, SEO, data analysis, and insight generation.',
    iconPath: `${roleIconBase}/druid.svg`,
    slug: 'druid',
  },
  {
    title: 'Paladin',
    type: 'Backend Dev',
    group: 'builder',
    description: 'Backend systems, APIs, infrastructure logic, and server-side application work.',
    iconPath: `${roleIconBase}/paladin.svg`,
    slug: 'paladin',
  },
  {
    title: 'Necromancer',
    type: 'DevOps',
    group: 'builder',
    description: 'Deployment, technical configuration, monitoring, and systems optimization.',
    iconPath: `${roleIconBase}/necromancer.svg`,
    slug: 'necromancer',
  },
  {
    title: 'Ranger',
    type: 'UX/User Testing',
    group: 'builder',
    description: 'User experience, research, prototyping, usability, and product feedback loops.',
    iconPath: `${roleIconBase}/ranger.svg`,
    slug: 'ranger',
  },
  {
    title: 'Warrior',
    type: 'Frontend Dev',
    group: 'builder',
    description: 'Frontend applications, interface implementation, React, CSS, and browser UX.',
    iconPath: `${roleIconBase}/warrior.svg`,
    slug: 'warrior',
  },
  {
    title: 'Wizard',
    type: 'Smart Contracts',
    group: 'builder',
    description: 'Solidity, Vyper, protocol logic, contract architecture, and onchain systems.',
    iconPath: `${roleIconBase}/wizard.svg`,
    slug: 'wizard',
  },
  {
    title: 'Cleric',
    type: 'Account Manager',
    group: 'builder',
    description: 'Client communication, delivery coordination, and relationship stewardship.',
    iconPath: `${roleIconBase}/cleric.svg`,
    slug: 'cleric',
  },
  {
    title: 'Hunter',
    type: 'BizDev',
    group: 'builder',
    description: 'Business development, partnerships, sales, and opportunity creation.',
    iconPath: `${roleIconBase}/hunter.svg`,
    slug: 'hunter',
  },
  {
    title: 'Monk',
    type: 'Project Manager',
    group: 'builder',
    description: 'Planning, budgeting, coordination, scoping, and delivery management.',
    iconPath: `${roleIconBase}/monk.svg`,
    slug: 'monk',
  },
  {
    title: 'Mystic Alchemist',
    type: 'DAO Consultant',
    group: 'builder',
    description: 'DAO strategy, governance design, token systems, and organizational consulting.',
    iconPath: `${roleIconBase}/alchemist.svg`,
    slug: 'mystic-alchemist',
  },
  {
    title: 'Apprentice',
    type: 'New Applicants',
    group: 'support',
    description: 'New contributors learning the RaidGuild network, process, and craft.',
    slug: 'apprentice',
  },
  {
    title: 'Angry Dwarf',
    type: 'Treasury',
    group: 'support',
    description: 'Finance, accounting, treasury management, and operational reporting.',
    iconPath: `${roleIconBase}/dwarf.svg`,
    slug: 'angry-dwarf',
  },
  {
    title: 'Bard',
    type: 'Marketing',
    group: 'support',
    description: 'Marketing, social media, storytelling, and community growth.',
    slug: 'bard',
  },
  {
    title: 'Rogue',
    type: 'Legal',
    group: 'support',
    description: 'Legal analysis, agreements, risk review, and policy support.',
    iconPath: `${roleIconBase}/rogue.svg`,
    slug: 'rogue',
  },
  {
    title: 'Scribe',
    type: 'Content Creator',
    group: 'support',
    description: 'Writing, publishing, podcasting, video, documentation, and editorial work.',
    iconPath: `${roleIconBase}/scribe.svg`,
    slug: 'scribe',
  },
  {
    title: 'Tavern Keeper',
    type: 'Community',
    group: 'support',
    description: 'Community operations, facilitation, onboarding, and member support.',
    iconPath: `${roleIconBase}/tavernkeeper.svg`,
    slug: 'tavern-keeper',
  },
  {
    title: 'Healer',
    type: 'Internal Ops',
    group: 'support',
    description: 'Internal operations, logistics, process improvement, and guild maintenance.',
    iconPath: `${roleIconBase}/healer.svg`,
    slug: 'healer',
  },
]
